"""Roles → API scopes, and the shared password-hash format (M5.1b).

Dashboard/API users carry a role; the API's permission system stays the M0.1
scope hierarchy. The mapping is fixed data, not configuration — a fork that
wants finer roles should extend the table here, in one place.

Password hashes use the exact format the dashboard introduced in M0.1
(`scrypt$<saltHex>$<hashHex>`, N=16384 r=8 p=1 dklen=64, node's scryptSync
defaults) so a hash generated by either side verifies on both.
"""

import hashlib
import hmac
import secrets

ROLES: tuple[str, ...] = ("owner", "operator", "viewer")

# owner → admin ⊃ operate ⊃ read (api/auth.py hierarchy)
ROLE_SCOPE: dict[str, str] = {
    "owner": "admin",
    "operator": "operate",
    "viewer": "read",
}

_SCRYPT_N = 16384
_SCRYPT_R = 8
_SCRYPT_P = 1
_SCRYPT_DKLEN = 64


def hash_password(plain: str) -> str:
    salt = secrets.token_bytes(16)
    derived = hashlib.scrypt(
        plain.encode(), salt=salt, n=_SCRYPT_N, r=_SCRYPT_R, p=_SCRYPT_P,
        dklen=_SCRYPT_DKLEN,
    )
    return f"scrypt${salt.hex()}${derived.hex()}"


def verify_password(plain: str, stored: str | None) -> bool:
    """Constant-time verify; malformed/absent hashes verify False, never raise —
    an SSO-only user (password_hash NULL) simply cannot password-login."""
    if not stored:
        return False
    parts = stored.split("$")
    if len(parts) != 3 or parts[0] != "scrypt":
        return False
    try:
        salt = bytes.fromhex(parts[1])
        expected = bytes.fromhex(parts[2])
        derived = hashlib.scrypt(
            plain.encode(), salt=salt, n=_SCRYPT_N, r=_SCRYPT_R, p=_SCRYPT_P,
            dklen=len(expected) or _SCRYPT_DKLEN,
        )
    except (ValueError, TypeError):
        return False
    return hmac.compare_digest(expected, derived)
