"""Alembic environment.

Wires migrations to the app's own configuration and models so there is a single
source of truth:
  - the database URL comes from craftsman Settings, not alembic.ini
  - the target schema is craftsman.core.models.Base.metadata
  - pgvector is imported so autogenerated scripts can reference Vector columns
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Import so the Vector type is registered for autogenerate/rendering.
import pgvector.sqlalchemy  # noqa: F401

from craftsman.core.config import get_settings
from craftsman.core.models import Base

config = context.config

# Point Alembic at the app's real database URL — unless a caller already supplied one
# (e.g. the migration tests inject a throwaway DB via cfg.set_main_option).
if not config.get_main_option("sqlalchemy.url"):
    config.set_main_option("sqlalchemy.url", get_settings().database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection (`alembic upgrade --sql`)."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        compare_server_default=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
