"""Alembic migration tests: upgrade → head, downgrade round-trip, and no drift.

These run against a dedicated throwaway database so they never touch the fast
create_all fixture used by the rest of the suite. Skips cleanly if Postgres is absent.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from craftsman.core.models import Base
from tests.conftest import TEST_DB_URL

MIG_DB = "craftsman_migtest"
MIG_URL = TEST_DB_URL.rsplit("/", 1)[0] + f"/{MIG_DB}"
ADMIN_URL = TEST_DB_URL.rsplit("/", 1)[0] + "/postgres"
REPO_ROOT = Path(__file__).resolve().parents[2]


def _alembic_cfg() -> Config:
    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", MIG_URL)  # env.py honors this
    return cfg


@pytest.fixture()
def mig_db():
    """A freshly-created empty database for one migration test, dropped afterward."""
    try:
        admin = create_engine(ADMIN_URL, isolation_level="AUTOCOMMIT")
        with admin.connect() as conn:
            conn.execute(text(f"DROP DATABASE IF EXISTS {MIG_DB} WITH (FORCE)"))
            conn.execute(text(f"CREATE DATABASE {MIG_DB}"))
    except Exception:
        pytest.skip("Postgres not reachable — skipping migration tests")
    yield MIG_URL
    with admin.connect() as conn:
        conn.execute(text(f"DROP DATABASE IF EXISTS {MIG_DB} WITH (FORCE)"))
    admin.dispose()


def test_upgrade_head_builds_expected_schema(mig_db):
    command.upgrade(_alembic_cfg(), "head")

    engine = create_engine(mig_db)
    try:
        tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    # every model table exists, plus Alembic's own bookkeeping table
    assert set(Base.metadata.tables).issubset(tables)
    assert "api_keys" in tables  # M0.1's table is captured in the baseline
    assert "alembic_version" in tables

    engine = create_engine(mig_db)
    try:
        cols = {c["name"] for c in inspect(engine).get_columns("companies")}
    finally:
        engine.dispose()
    assert "embedding" in cols  # pgvector column created (extension applied)


def test_downgrade_base_then_reupgrade(mig_db):
    cfg = _alembic_cfg()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    engine = create_engine(mig_db)
    try:
        remaining = [t for t in inspect(engine).get_table_names() if t != "alembic_version"]
    finally:
        engine.dispose()
    assert remaining == []  # downgrade removed every app table

    command.upgrade(cfg, "head")  # must cleanly re-apply
    engine = create_engine(mig_db)
    try:
        assert "api_keys" in inspect(engine).get_table_names()
    finally:
        engine.dispose()


def test_no_drift_between_models_and_migrations(mig_db):
    """If a model changes without a matching migration, this fails — the guard the
    roadmap asks for. `alembic check` raises when head and the models diverge."""
    cfg = _alembic_cfg()
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"models and migrations are out of sync — add a migration:\n{exc}")
