"""concurrency counters and idempotency index

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-21 12:26:11.158681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('sent_today', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('messages', sa.Column('step_order', sa.Integer(), nullable=True))
    op.create_index('uq_outbound_step', 'messages', ['enrollment_id', 'step_order'], unique=True, postgresql_where=sa.text("direction = 'outbound'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_outbound_step', table_name='messages', postgresql_where=sa.text("direction = 'outbound'"))
    op.drop_column('messages', 'step_order')
    op.drop_column('campaigns', 'sent_today')
    # ### end Alembic commands ###
